### ISSUE TITLE
deviceApi.on... unable to make it work

### ISSUE THREAD

**Issue by Mimerel** [denwilliams/node-zway#2]
Hello,

I am trying to get the following code working but keep getting an error..
    
```
deviceApi.on('2.50.*', data => {
        console.log('event data:', data);
    });
```

I keep getting the following error message : 

>    throw new Error('on only accepts instances of Function');
>       ^
> Error: on only accepts instances of Function

And I don't really know what to do.

I manage to get the deviceApi.onAny working perfectly..

Could you give me an idea on what I am doing wrong?

Thank you very much

**Comment by tomkubitza** [comment]
+1

**Comment by Mimerel** [comment]
Ok, error in the readme file.

should be :
`
deviceApi.on('2' , '50' , '*' , data => {
        console.log('event data:', data);
    });
`
